[project]
name = "DataToSeatable"
version = "0.1.0"
description = ""

dependencies = [
python = "^3.9"
pychrome = "^0.2.4"
seatable-api = "^3.0.0"
dotenv = "^0.9.9"
playwright = "1.50.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
