[project]
name = "DataToSeatable"
version = "0.1.0"
description = "THS Spider for data collection"
dependencies = [
    "seatable-api",
    "python-dotenv",
    "playwright"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
