[project]
name = "Run THS Spider"
version = "0.1.0"
description = "THS Spider for data collection"
dependencies = [
    "playwright==2.9.3",    
    "seatable-api==0.9.1",  
    "python-dotenv==0.19.0"  
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
