[project]
name = "THSspider_LKX"
version = "0.1.0"
description = "THS Spider for data collection"
dependencies = [    
    "seatable-api",  
    "python-dotenv"  
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
