
name: THS Spider Runner
on:
  workflow_dispatch:    
  schedule:
    - cron: '0 4 * * *'    # 每天北京时间 12:00 运行

jobs:
  run-ths-spider:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install uv
        run: pip install uv

      - name: Install deps
        run: |
          uv sync
          playwright install chromium
          
      - name: Run THS Spider
        env:
          SEATABLE_API_TOKEN: ${{ secrets.SEATABLE_API_TOKEN }}
          SEATABLE_SERVER_URL: ${{ vars.SEATABLE_SERVER_URL }}
          PYTHONIOENCODING: utf-8
          PYTHONUTF8: 1
        run: |
          chcp 65001
          uv run python THSspider_LKX.py
          
      - name: Handle errors
        if: failure()
        run: |
          echo "Spider run failed, please check the logs"
